# Generated by Django 4.2.5 on 2023-11-30 09:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_rename_mathcall_snippet2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snippet2',
            new_name='Snippet',
        ),
    ]
