# Generated by Django 4.1.3 on 2023-12-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_company_company_ivff_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='domain',
            field=models.TextField(null=True),
        ),
    ]
